library(GGally)
library(ggplot2)
library(psych)
library(cluster)
library(dendextend)
library(colorspace)
library(factoextra)
library(class)
library(rpart)
library(rpart.plot)
library(caret)
library(ggfortify)
library(randomForest)
library(dplyr)
library(tidyr)

setwd("C:/Users/brook/Downloads/Data Science/assignment3")

house.data <- read.csv("real_estate_dataset.csv")
